package com.rpst.yc.client.ui;


import java.awt.GraphicsDevice;
import java.awt.Robot;
import java.awt.Window;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Time;
import javax.swing.JFrame;
import java.util.Arrays;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
        

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pavan Poudel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.addKeyListener(new KeyAdapter() {});
    }
public static int start = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_welcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        lbl_nomatch = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_option = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_serverIP = new javax.swing.JTextField();
        btn_connect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");
        setAlwaysOnTop(true);
        setExtendedState(2);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(380, 308));
        setResizable(false);
        setState(2);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_welcome.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(153, 153, 0));
        lbl_welcome.setText("Welcome to Yellow Cafe");
        getContentPane().add(lbl_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 298, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 230, -1));

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel5.setText("Default Username/Password are:"); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));

        lbl_nomatch.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lbl_nomatch.setText("yc/yc"); // NOI18N
        jPanel1.add(lbl_nomatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 210, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 410, 180));

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 100, 30));

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 100, 30));

        btn_option.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_option.setText("Option >>");
        btn_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_optionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Server IP Address: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txt_serverIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_serverIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 190, -1));

        btn_connect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });
        getContentPane().add(btn_connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 100, 30));

        setSize(new java.awt.Dimension(406, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static fullpage f = new fullpage();
    public static Login l = new Login();
    private static boolean isPasswordCorrect(char[] input) {
    boolean isCorrect = true;
    char[] correctPassword = { 'y', 'c' };

    if (input.length != correctPassword.length) {
        isCorrect = false;
    } else {
        isCorrect = Arrays.equals (input, correctPassword);
    }

    //Zero out the password.
    Arrays.fill(correctPassword,'0');

    return isCorrect;
}
    
        GraphicsDevice myDevice = null;
        Window myWindow = null;  
    private void validity()
    {
        String username=txt_username.getText();
        char[] p=txt_password.getPassword();
       
        if(username.equals("yc") && isPasswordCorrect(p)){
            
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                    final ClientUIMain c = new ClientUIMain();
                    c.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                    
                    c.lbl_prepaid_amt.setText("00.00");
                    c.lbl_traffic_amt.setText("00.00");
                    c.lbl_others_amt.setText("00.00");
                    c.lbl_total_amt.setText("10.00");
                    c.lbl_balance.setText("00.00");
                    
                    c.lbl_loginId.setText("yc");
                    c.lbl_name.setText("YelloCafe");
                    c.lbl_pricing.setText("Employee");
                    c.lbl_payment.setText("Post-Paid");
                    
                    Timer timer=new Timer();
                    final Time t1=new Time(0,0,0);
                    timer.schedule(new TimerTask() {
                    
                    public void run() {
                    if(start==1)
                    {
                        t1.setTime(t1.getTime());
                    }
                    else{
                  t1.setTime(t1.getTime() + 1000);}
                    
                 c.lbl_time.setText(String.valueOf(t1));
                 if(t1.getMinutes()<10){
                     c.lbl_time_amt.setText("10.00");
                     c.lbl_total_amt.setText("10.00");
                 }
                 else if(t1.getMinutes()>=10 && t1.getMinutes()<30){
                     c.lbl_time_amt.setText("20.00");
                     c.lbl_total_amt.setText("20.00");
                 }
                 else{
                     c.lbl_time_amt.setText("30.00");
                    c.lbl_total_amt.setText("30.00");
                 }
                }
              }, 0,1000);
                    
                    c.setVisible(true); 
                    
                    
                    f.dispose();
                    f.setVisible(false);
                    
            }
            
        });
            this.dispose();
            //this.setVisible(false);
            fullpage f1 = ClientUIMain.f;
           f1.setVisible(false);
             
        }
        else
        { 
           //lbl_nomatch.setText("Sorry, username or password do not matched. Please try again.");
           JOptionPane.showMessageDialog(rootPane,"Invalid username or password.", "YelloCafe", 0);
           
        }
    }
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        validity();
        
               
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        txt_username.setText(null);
        txt_password.setText(null);
        //lbl_nomatch.setText(null);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
        validity();
    }//GEN-LAST:event_txt_passwordActionPerformed

    private int check = 0;
    private void btn_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_optionActionPerformed
       if(check==0){
           this.setSize(390, 440);
            btn_option.setText("<<..");
            check=1;
       }
       else{
           this.setSize(390, 330);
           btn_option.setText("Option >>");
            check=0;
       }
    }//GEN-LAST:event_btn_optionActionPerformed

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_connectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    f.setVisible(true);
                    
                    l.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                    l.setSize(390,330);
                    l.setVisible(true);
                    l.addKeyListener(new KeyAdapter() {

                    @Override
                    public void keyPressed(KeyEvent e) {
                        e.consume();
                        
                    }
                    
                    });
                    try{
                        Robot rb=new Robot();
                        rb.keyRelease(KeyEvent.VK_ALT);
                        rb.keyRelease(KeyEvent.VK_TAB);
                    }
                    catch(Exception ex){
                        
                    }
              }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_connect;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_option;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_nomatch;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_serverIP;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
