/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpst.yc.server.ui;

import com.rpst.yc.database.DBQuery;
import com.rpst.yc.database.*;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Pavan Poudel
 */
public class Create_Session extends javax.swing.JFrame {

    /**
     * Creates new form Create_Session
     */
    public Create_Session() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        btn_addnew = new javax.swing.JButton();
        cbo_users = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbo_bandwidth = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        txt_age = new javax.swing.JTextField();
        txt_fullname = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        cbo_pricing = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbo_time = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_currBalance = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_terminal = new javax.swing.JTextField();

        setTitle("Create Sesion");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(590, 630));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 140));

        lbl_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_user.setText("User");
        getContentPane().add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btn_addnew.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_addnew.setText("Add New ...");
        btn_addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addnewActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, 30));

        cbo_users.setEditable(true);
        cbo_users.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbo_users.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guest", "User1", "User2", "User3" }));
        cbo_users.setAutoscrolls(true);
        getContentPane().add(cbo_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 280, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Select Users ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Select Bandwidth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Fullname");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Age");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 540, 10));

        cbo_bandwidth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbo_bandwidth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "128 Kbps", "256 Kbps", "512 Kbps", "1 Mbps", " " }));
        getContentPane().add(cbo_bandwidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 230, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Client Terminal");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        btn_create.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        getContentPane().add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 100, 30));

        txt_age.setEditable(false);
        txt_age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 230, 30));

        txt_fullname.setEditable(false);
        txt_fullname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 230, 30));

        txt_address.setEditable(false);
        txt_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 230, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 540, 10));

        cbo_pricing.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbo_pricing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard", "Employee", "Student" }));
        getContentPane().add(cbo_pricing, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 230, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Pricing");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        cbo_time.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbo_time.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unlimited", "15 Minutes", "30 Minutes", "1 Hour", "2 Hours", "3 Hours" }));
        getContentPane().add(cbo_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 230, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Time");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Current Balance");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        txt_currBalance.setEditable(false);
        txt_currBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_currBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 230, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 540, 10));

        txt_terminal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_terminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 230, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    static int terminal=1;
    static int i=1;
    DBQuery dq =new DBQuery();
    SessionData sd;
    public static JPanel_BusyTerminal[] bg = new JPanel_BusyTerminal[50];
    public static JPanel_BusyTerminal[] getTerminal()
    {
        return bg;
    }
    
    private void input()
    {
        String uuid = getUUID();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date startTime = new Date();
        String st = dateFormat.format(startTime);
        sd = new SessionData(uuid, lbl_user.getText(), st, "", txt_terminal.getText(), 0);
    }
    
    private String getUUID()
    {
        String uid = "UUID_" + i;//function call for uuid
        i++;
        return uid;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addnewActionPerformed
        UserRegistration usr = new UserRegistration();
        usr.setVisible(true);
    }//GEN-LAST:event_btn_addnewActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        input();
        String msg = dq.SaveSession(sd);
        JOptionPane.showMessageDialog(rootPane, msg);
        this.setVisible(false);
    }//GEN-LAST:event_btn_createActionPerformed
    
    private String setTrafficCost()
    {
        String traffic;
        if(cbo_bandwidth.getSelectedItem().toString() == "128 Kbps")
        {
            traffic = "0";
        }
        else if(cbo_bandwidth.getSelectedItem().toString() == "256 Kbps")
        {
            traffic = "10";
        }
        else if(cbo_bandwidth.getSelectedItem().toString() == "512 Kbps")
        {
            traffic = "20";
        }
        else
        {
            traffic = "40";
        }
        return traffic;
    } 
    
    public void getAction(final JButton b, final Create_Session cs)
    {
        btn_create.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                bg[terminal] = new JPanel_BusyTerminal();
                bg[terminal].lbl_prepaid_amt.setText(txt_currBalance.getText());
                bg[terminal].lbl_time_amt.setText("10 (Min.)");
                bg[terminal].lbl_traffic_amt.setText(setTrafficCost());
                bg[terminal].lbl_others_amt.setText("0");
                bg[terminal].lbl_total_amt.setText("10");
                bg[terminal].lbl_balance.setText("-10");
                bg[terminal].lbl_time.setText(cbo_time.getSelectedItem().toString());
                bg[terminal].jProgressBar1.setMaximum(900);
                bg[terminal].jProgressBar1.setValue(100);
                Main.getInstance().panel_bgterminal.removeAll();
                Main.getInstance().panel_bgterminal.add(bg[terminal]);
                Main.getInstance().panel_bgterminal.validate();
                terminal++;
                
                b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rpst/yc/images/desktopon.png")));
                b.setSelected(true);
                cs.setVisible(false);
                }
            });
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Session().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addnew;
    private javax.swing.JButton btn_create;
    private javax.swing.JComboBox cbo_bandwidth;
    private javax.swing.JComboBox cbo_pricing;
    private javax.swing.JComboBox cbo_time;
    private javax.swing.JComboBox cbo_users;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_currBalance;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JTextField txt_terminal;
    // End of variables declaration//GEN-END:variables
}
