/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpst.yc.server.ui;

import java.awt.BorderLayout;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Pavan Poudel
 */
public class Details extends javax.swing.JFrame {

    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_compname5 = new javax.swing.JTextField();
        txt_compname4 = new javax.swing.JTextField();
        txt_compname3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_compname6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_compname7 = new javax.swing.JTextField();
        txt_compname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ipaddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btn_screenCapture = new javax.swing.JButton();
        btn_chat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_cancel = new javax.swing.JButton();
        txt_compname8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(1380, 760));
        setPreferredSize(new java.awt.Dimension(1260, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_compname5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_compname5.setForeground(new java.awt.Color(0, 102, 102));
        txt_compname5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_compname5.setName("txt_compname"); // NOI18N
        getContentPane().add(txt_compname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 210, 20));

        txt_compname4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_compname4.setForeground(new java.awt.Color(0, 102, 102));
        txt_compname4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_compname4.setName("txt_compname"); // NOI18N
        getContentPane().add(txt_compname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 210, 20));

        txt_compname3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_compname3.setForeground(new java.awt.Color(0, 102, 102));
        txt_compname3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_compname3.setName("txt_compname"); // NOI18N
        getContentPane().add(txt_compname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 210, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select the Terminal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        txt_compname6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_compname6.setForeground(new java.awt.Color(0, 102, 102));
        txt_compname6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_compname6.setName("txt_compname"); // NOI18N
        getContentPane().add(txt_compname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 210, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Space Available:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        txt_compname7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_compname7.setForeground(new java.awt.Color(0, 102, 102));
        txt_compname7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_compname7.setName("txt_compname"); // NOI18N
        getContentPane().add(txt_compname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 210, 20));

        txt_compname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_compname.setForeground(new java.awt.Color(0, 102, 102));
        txt_compname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_compname.setName("txt_compname"); // NOI18N
        getContentPane().add(txt_compname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Internet Access:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Available Bandwidth:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        txt_ipaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ipaddress.setForeground(new java.awt.Color(0, 102, 102));
        txt_ipaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_ipaddress.setName("txt_compname"); // NOI18N
        getContentPane().add(txt_ipaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 210, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("IP address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Processor:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Memory (RAM):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rpst/yc/images/desktop8.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 120));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 210, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Computer Name: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        btn_screenCapture.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_screenCapture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rpst/yc/images/screencapture.png"))); // NOI18N
        btn_screenCapture.setText("Screen Capture");
        btn_screenCapture.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_screenCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_screenCaptureActionPerformed(evt);
            }
        });
        getContentPane().add(btn_screenCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 220, 40));

        btn_chat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_chat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rpst/yc/images/chat.jpg"))); // NOI18N
        btn_chat.setText("Chat");
        btn_chat.setMargin(new java.awt.Insets(2, 2, 2, 70));
        btn_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 190, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 410, 470));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 430, 470));

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 160, 50));

        txt_compname8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_compname8.setForeground(new java.awt.Color(0, 102, 102));
        txt_compname8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_compname8.setName("txt_compname"); // NOI18N
        getContentPane().add(txt_compname8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Operating System:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chatActionPerformed
        JPanel_Chat chat = new JPanel_Chat();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(chat);
        jPanel1.validate();
        jPanel1.setVisible(true);
        //this.setVisible(true);
    }//GEN-LAST:event_btn_chatActionPerformed

    private void btn_screenCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_screenCaptureActionPerformed
        JPanel_ScreenCapture sc = new JPanel_ScreenCapture();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(sc);
        jPanel2.validate();
        jPanel2.setVisible(true);
    }//GEN-LAST:event_btn_screenCaptureActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_chat;
    private javax.swing.JButton btn_screenCapture;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_compname;
    private javax.swing.JTextField txt_compname3;
    private javax.swing.JTextField txt_compname4;
    private javax.swing.JTextField txt_compname5;
    private javax.swing.JTextField txt_compname6;
    private javax.swing.JTextField txt_compname7;
    private javax.swing.JTextField txt_compname8;
    private javax.swing.JTextField txt_ipaddress;
    // End of variables declaration//GEN-END:variables
}
