/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpst.yc.server.ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Pavan Poudel
 */
public class FrmCommunication extends javax.swing.JDialog {

    /**
     * Creates new form FrmCommunication
     */
    public FrmCommunication(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_writePane = new javax.swing.JTextPane();
        btn_send = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_chatHistory = new javax.swing.JTextPane();
        btn_chat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btn_screenCapture = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();
        lbl_snapshot = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        txt_compname = new javax.swing.JTextField();
        txt_ipaddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_profile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_macaddr = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_terminal = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Communication");
        setMinimumSize(new java.awt.Dimension(1010, 720));
        setPreferredSize(new java.awt.Dimension(1010, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Terminal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rpst/yc/images/desktop8.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 110));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Chat History");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 48, -1, -1));

        jScrollPane1.setViewportView(txt_writePane);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 320, 70));

        btn_send.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        jPanel1.add(btn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 70, 70));

        jScrollPane3.setViewportView(txt_chatHistory);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 390, 330));

        btn_chat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_chat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rpst/yc/images/chat.jpg"))); // NOI18N
        btn_chat.setText("Chat");
        btn_chat.setBorderPainted(false);
        btn_chat.setContentAreaFilled(false);
        btn_chat.setFocusPainted(false);
        btn_chat.setFocusable(false);
        btn_chat.setMargin(new java.awt.Insets(2, 2, 2, 40));
        btn_chat.setRequestFocusEnabled(false);
        btn_chat.setRolloverEnabled(false);
        jPanel1.add(btn_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 408, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 410, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 410, 490));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_screenCapture.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_screenCapture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rpst/yc/images/screencapture.png"))); // NOI18N
        btn_screenCapture.setText("Screen Capture");
        btn_screenCapture.setBorderPainted(false);
        btn_screenCapture.setContentAreaFilled(false);
        btn_screenCapture.setDefaultCapable(false);
        btn_screenCapture.setFocusPainted(false);
        btn_screenCapture.setFocusable(false);
        btn_screenCapture.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_screenCapture.setRequestFocusEnabled(false);
        btn_screenCapture.setRolloverEnabled(false);
        jPanel2.add(btn_screenCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 508, 40));

        btn_stop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_stop.setForeground(new java.awt.Color(204, 0, 0));
        btn_stop.setText("Stop");
        jPanel2.add(btn_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 90, 30));

        btn_start.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_start.setForeground(new java.awt.Color(0, 153, 0));
        btn_start.setText("Capture");
        jPanel2.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, 30));

        lbl_snapshot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lbl_snapshot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 488, 370));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 510, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 510, 490));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_compname.setEditable(false);
        txt_compname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_compname.setForeground(new java.awt.Color(0, 102, 102));
        txt_compname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_compname.setName("txt_compname"); // NOI18N
        jPanel4.add(txt_compname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, 20));

        txt_ipaddress.setEditable(false);
        txt_ipaddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ipaddress.setForeground(new java.awt.Color(0, 102, 102));
        txt_ipaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_ipaddress.setName("txt_compname"); // NOI18N
        jPanel4.add(txt_ipaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Profile");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Computer Name: ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txt_profile.setEditable(false);
        txt_profile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_profile.setForeground(new java.awt.Color(0, 102, 102));
        txt_profile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_profile.setName("txt_compname"); // NOI18N
        jPanel4.add(txt_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("IP Address");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txt_macaddr.setEditable(false);
        txt_macaddr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_macaddr.setForeground(new java.awt.Color(0, 102, 102));
        txt_macaddr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_macaddr.setName("txt_compname"); // NOI18N
        jPanel4.add(txt_macaddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 190, 20));

        txt_username.setEditable(false);
        txt_username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_username.setForeground(new java.awt.Color(0, 102, 102));
        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_username.setName("txt_compname"); // NOI18N
        jPanel4.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 190, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Username");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("MAC Address");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 620, 100));

        txt_terminal.setEditable(false);
        getContentPane().add(txt_terminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, 30));

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 0, 0));
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 650, 100, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chat()
    {
        String msg = txt_writePane.getText();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String dt = (dateFormat.format(date));
        String chatHistory =txt_chatHistory.getText() + " \n------------------------------------------------------ " + dt + "\nServer:- " + msg ;
       
        txt_chatHistory.setText(chatHistory);
        txt_writePane.setText(null);
    }
    private void chatClient(String msg)
    {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String dt = (dateFormat.format(date));
        String chatHistory =txt_chatHistory.getText() + " \n------------------------------------------------------ " + dt + "\nServer:- " + msg ;
       
        txt_chatHistory.setText(chatHistory);
        txt_writePane.setText(null);
    }
    
    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        chat();
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCommunication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCommunication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCommunication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCommunication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCommunication dialog = new FrmCommunication(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_chat;
    private javax.swing.JButton btn_screenCapture;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_snapshot;
    private javax.swing.JTextPane txt_chatHistory;
    private javax.swing.JTextField txt_compname;
    private javax.swing.JTextField txt_ipaddress;
    private javax.swing.JTextField txt_macaddr;
    private javax.swing.JTextField txt_profile;
    private javax.swing.JTextField txt_terminal;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextPane txt_writePane;
    // End of variables declaration//GEN-END:variables
}
