/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpst.yc.server.ui;

/**
 *
 * @author Pavan Poudel
 */
public class JPanel_ScreenCapture extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_ScreenCapture
     */
    public JPanel_ScreenCapture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_stop = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(410, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 430, 370));

        btn_stop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_stop.setForeground(new java.awt.Color(204, 0, 0));
        btn_stop.setText("Stop");
        add(btn_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 90, 40));

        btn_start.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_start.setForeground(new java.awt.Color(0, 153, 0));
        btn_start.setText("Start");
        add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, 40));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
