/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpst.yc.server.ui;

import java.awt.Color;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;

/**
 *
 * @author Pavan Poudel
 */
public class JPanel_Chat extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Chat
     */
    public JPanel_Chat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_writePane = new javax.swing.JTextPane();
        btn_send = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_chatHistory = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(410, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Chat History");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jScrollPane1.setViewportView(txt_writePane);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 320, 70));

        btn_send.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        add(btn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 70, 70));

        jScrollPane3.setViewportView(txt_chatHistory);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 390, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void chat()
    {
        String msg = txt_writePane.getText();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String dt = (dateFormat.format(date));
        String chatHistory =txt_chatHistory.getText() + " \n------------------------------------------------------ " + dt + "\nServer:- " + msg ;
       
        txt_chatHistory.setText(chatHistory);
        txt_writePane.setText(null);
    }
    
    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        chat();
    }//GEN-LAST:event_btn_sendActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txt_chatHistory;
    private javax.swing.JTextPane txt_writePane;
    // End of variables declaration//GEN-END:variables
}
