/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpst.yc.server.ui;

/**
 *
 * @author Pavan Poudel
 */
public class JPanel_BusyTerminal extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_BusyTerminal
     */
    public JPanel_BusyTerminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_others_amt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        lbl_prepaid_amt = new javax.swing.JLabel();
        jlabel7 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_total_amt = new javax.swing.JLabel();
        lbl_time_amt = new javax.swing.JLabel();
        lbl_traffic_amt = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_balance = new javax.swing.JLabel();
        jlabel11 = new javax.swing.JLabel();
        jlabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jProgressBar1 = new javax.swing.JProgressBar();
        lbl_time1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_others_amt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_others_amt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_others_amt.setText("-- amount --");
        add(lbl_others_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 80, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Pre-paid :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        lbl_prepaid_amt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_prepaid_amt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_prepaid_amt.setText("-- amount --");
        add(lbl_prepaid_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, -1));

        jlabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel7.setText("Time :");
        add(jlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, -1));

        jlabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel6.setText("Traffic :");
        add(jlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, -1));

        lbl_total_amt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_total_amt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_total_amt.setText("-- amount --");
        add(lbl_total_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 80, -1));

        lbl_time_amt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_time_amt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_time_amt.setText("-- amount --");
        add(lbl_time_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 80, -1));

        lbl_traffic_amt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_traffic_amt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_traffic_amt.setText("-- amount --");
        add(lbl_traffic_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 80, -1));

        jlabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel9.setText("Others :");
        add(jlabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, -1));

        lbl_time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(0, 102, 0));
        lbl_time.setText("Time");
        add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 170, -1));

        lbl_balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_balance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_balance.setText("-- amount --");
        add(lbl_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        jlabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel11.setText("Total");
        add(jlabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        jlabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel12.setText("Balance");
        add(jlabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, 10));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 200, 210, -1));

        lbl_time1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_time1.setForeground(new java.awt.Color(0, 102, 0));
        lbl_time1.setText("Time:");
        add(lbl_time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    protected javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlabel11;
    private javax.swing.JLabel jlabel12;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabel9;
    public javax.swing.JLabel lbl_balance;
    public javax.swing.JLabel lbl_others_amt;
    public javax.swing.JLabel lbl_prepaid_amt;
    public javax.swing.JLabel lbl_time;
    public javax.swing.JLabel lbl_time1;
    public javax.swing.JLabel lbl_time_amt;
    public javax.swing.JLabel lbl_total_amt;
    public javax.swing.JLabel lbl_traffic_amt;
    // End of variables declaration//GEN-END:variables
}
