/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rpst.yc.server.ui;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Pavan Poudel
 */
public class UserRegistration extends javax.swing.JFrame {

    /**
     * Creates new form UserRegistration
     */
    public UserRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panel_access = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_loginId = new javax.swing.JTextField();
        txt_fullname = new javax.swing.JTextField();
        txt_balance = new javax.swing.JTextField();
        cbo_payment = new javax.swing.JComboBox();
        txt_idnumber = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_image = new javax.swing.JButton();
        cbo_usertype = new javax.swing.JComboBox();
        btn_ok = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        cbo_identity = new javax.swing.JComboBox();
        txt_imagepath = new javax.swing.JTextField();
        lbl_photo = new javax.swing.JLabel();
        panel_personal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdo_male = new javax.swing.JRadioButton();
        rdo_female = new javax.swing.JRadioButton();
        txt_age = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();

        setTitle("User Registration");
        setLocationByPlatform(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        panel_access.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Balance");
        panel_access.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Login ID");
        panel_access.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Identity");
        panel_access.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Full Name");
        panel_access.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("User Type");
        panel_access.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("ID Number");
        panel_access.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Payment");
        panel_access.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txt_loginId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_loginId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginIdActionPerformed(evt);
            }
        });
        panel_access.add(txt_loginId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 220, 30));

        txt_fullname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fullnameActionPerformed(evt);
            }
        });
        panel_access.add(txt_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 290, 30));

        txt_balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_balanceActionPerformed(evt);
            }
        });
        panel_access.add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 290, 30));

        cbo_payment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbo_payment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pre-paid", "Post-paid" }));
        panel_access.add(cbo_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 290, 30));

        txt_idnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panel_access.add(txt_idnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel_access.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 10, 150));

        btn_image.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_image.setText("Image ...");
        btn_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imageActionPerformed(evt);
            }
        });
        panel_access.add(btn_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, -1));

        cbo_usertype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbo_usertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Other", "Employee", "Student" }));
        panel_access.add(cbo_usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 290, 30));

        btn_ok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ok.setText("Ok >>");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        panel_access.add(btn_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 90, 30));
        panel_access.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 480, -1));

        cbo_identity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbo_identity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID card", "Lisence", "Citizenship", "Other" }));
        panel_access.add(cbo_identity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, 30));

        txt_imagepath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_imagepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_imagepathActionPerformed(evt);
            }
        });
        panel_access.add(txt_imagepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 360, 30));

        lbl_photo.setText("                Photo");
        panel_access.add(lbl_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 34, 130, 120));

        jTabbedPane2.addTab("Access", panel_access);

        panel_personal.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        panel_personal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Description");
        panel_personal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Gender");
        panel_personal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Age");
        panel_personal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Phone");
        panel_personal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email");
        panel_personal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Address");
        panel_personal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        rdo_male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdo_male.setText("Male");
        rdo_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_maleActionPerformed(evt);
            }
        });
        panel_personal.add(rdo_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        rdo_female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdo_female.setText("Female");
        rdo_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_femaleActionPerformed(evt);
            }
        });
        panel_personal.add(rdo_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        txt_age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        panel_personal.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 93, 260, 30));

        txt_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panel_personal.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 143, 260, 30));

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panel_personal.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 193, 260, 30));

        txt_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(txt_address);

        panel_personal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 350, 70));

        txt_description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(txt_description);

        panel_personal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 350, 90));
        panel_personal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 480, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        panel_personal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 90, 30));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setText("save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        panel_personal.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 90, 30));

        jTabbedPane2.addTab("Personal", panel_personal);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_femaleActionPerformed
        rdo_female.setSelected(true);
        rdo_male.setSelected(false);
    }//GEN-LAST:event_rdo_femaleActionPerformed

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void txt_loginIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginIdActionPerformed

    private void txt_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fullnameActionPerformed

    private void txt_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_balanceActionPerformed

    private void rdo_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_maleActionPerformed
        rdo_male.setSelected(true);
        rdo_female.setSelected(false);
    }//GEN-LAST:event_rdo_maleActionPerformed

    private void txt_imagepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_imagepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_imagepathActionPerformed

    public String Chooser() {
        JFileChooser chooser = new JFileChooser();
        String fileName;
        int r = chooser.showOpenDialog(new JFrame());
        if (r == JFileChooser.APPROVE_OPTION) {
            fileName = chooser.getSelectedFile().getPath();
            return fileName;
        }
        else 
        {
            return null;
        }
        
    }
    private void btn_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageActionPerformed
        String path = Chooser();
        txt_imagepath.setText(path);
        ImageIcon ic = new javax.swing.ImageIcon((txt_imagepath.getText()));
        //lbl_photo.s
        lbl_photo.setIcon(new javax.swing.ImageIcon((txt_imagepath.getText())));
        
        lbl_photo.setVisible(true);
//        JDialog dg = new JDialog();
//        dg.setVisible(true);
    }//GEN-LAST:event_btn_imageActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
       jTabbedPane2.setSelectedIndex(jTabbedPane2.getSelectedIndex() + 1);
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegistration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_image;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbo_identity;
    private javax.swing.JComboBox cbo_payment;
    private javax.swing.JComboBox cbo_usertype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JPanel panel_access;
    private javax.swing.JPanel panel_personal;
    private javax.swing.JRadioButton rdo_female;
    private javax.swing.JRadioButton rdo_male;
    private javax.swing.JTextPane txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextPane txt_description;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JPasswordField txt_idnumber;
    private javax.swing.JTextField txt_imagepath;
    private javax.swing.JTextField txt_loginId;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
